services:
  app:

    build: .
    depends_on:
      - db

    ports:
      - 8000:8000

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5431
    volumes:
      - ./data/db:/var/lib/postgresql/data
