services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
    ports:
      - "8000:8000"

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=myplan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=onamotam
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
